displayName=Loot Case Opening
author=adnapPanda
description=A plugin that shows a case opening animation when receiving loot from CG,Moons,Barrows, and uniques from Raids
tags=loot case opening,case,opening,loot,reel,spin,tob,cox,toa,moons,barrows,cg,chambers,theatre,tombs,corrupted,gauntlet,xeric,amascut,sepulchre
version=1.1
plugins=com.lootcaseopening.LootCaseOpeningPlugin
build=standard