displayName=Loot Case Opening
author=adnapPanda
description=An example greeter plugin
tags=case,opening,loot,reel,tob,cox,toa,spin,moons,barrows
version=1.0
plugins=com.lootcaseopening.LootCaseOpeningPlugin
build=standard