displayName=Loot Case Opening
author=adnapPanda
description=A plugin that shows a case opening animation when receiving loot from CG,Moons,Barrows, and uniques from Raids
tags=case,opening,loot,reel,spin,tob,cox,toa,moons,barrows,cg,chambers,theatre,tombs,corrupted,gauntlet,xeric,amascut
version=1.0
plugins=com.lootcaseopening.LootCaseOpeningPlugin
build=standard